/* ============================================================
   AI Use Case Intake — Demo Data (25 sample records)
   Loaded by admin-script.js when ?demo=1 is in the URL
   ============================================================ */

const DEMO_DATA = [
  {
    ID: 1,
    Title: "AI-Assisted Lecture Summarisation Tool",
    Faculty_x002f_Department: "Faculty of Education",
    PersoninCharge_x0028_PIC_x0029_: "Prof. Winnie Lam",
    Email: "winnielam@hku.hk",
    Purpose: "Teaching & Learning",
    DeploymentType: "SaaS",
    AIPlatform: "OpenAI",
    AITools: "ChatGPT",
    AISubscriptionPlan: "ChatGPT Edu",
    EstimatedCost_x0028_HKD_x0029_: 18000,
    InvolvesPII: "No",
    Created: "2026-01-08T09:15:00Z"
  },
  {
    ID: 2,
    Title: "Automated Histology Slide Classifier",
    Faculty_x002f_Department: "Li Ka Shing Faculty of Medicine",
    PersoninCharge_x0028_PIC_x0029_: "Dr. Raymond Cheung",
    Email: "rcheung@hku.hk",
    Purpose: "Research",
    DeploymentType: "Inhouse",
    AIPlatform: "HKU HPC",
    AITools: "PyTorch / Custom CNN",
    AISubscriptionPlan: "",
    EstimatedCost_x0028_HKD_x0029_: 72000,
    InvolvesPII: "Yes",
    Created: "2026-01-14T11:30:00Z"
  },
  {
    ID: 3,
    Title: "Copilot for Student Email Triage",
    Faculty_x002f_Department: "ITS",
    PersoninCharge_x0028_PIC_x0029_: "Dicky Lee",
    Email: "dickyl@hku.hk",
    Purpose: "Admin",
    DeploymentType: "SaaS",
    AIPlatform: "Microsoft Azure",
    AITools: "MS Copilot",
    AISubscriptionPlan: "Microsoft 365 Copilot",
    EstimatedCost_x0028_HKD_x0029_: 42000,
    InvolvesPII: "Yes",
    Created: "2026-01-20T14:00:00Z"
  },
  {
    ID: 4,
    Title: "Legal Document Drafting Assistant",
    Faculty_x002f_Department: "Faculty of Law",
    PersoninCharge_x0028_PIC_x0029_: "Prof. Karen Ho",
    Email: "karenho@hku.hk",
    Purpose: "Teaching & Learning",
    DeploymentType: "SaaS",
    AIPlatform: "Anthropic",
    AITools: "Claude",
    AISubscriptionPlan: "Claude Pro",
    EstimatedCost_x0028_HKD_x0029_: 12000,
    InvolvesPII: "No",
    Created: "2026-01-25T10:00:00Z"
  },
  {
    ID: 5,
    Title: "Protein Folding Prediction Pipeline",
    Faculty_x002f_Department: "Faculty of Science",
    PersoninCharge_x0028_PIC_x0029_: "Dr. Alice Ng",
    Email: "aliceng@hku.hk",
    Purpose: "Research",
    DeploymentType: "Inhouse",
    AIPlatform: "HKU HPC",
    AITools: "AlphaFold2",
    AISubscriptionPlan: "",
    EstimatedCost_x0028_HKD_x0029_: 95000,
    InvolvesPII: "No",
    Created: "2026-02-03T09:45:00Z"
  },
  {
    ID: 6,
    Title: "Chatbot for IT Helpdesk",
    Faculty_x002f_Department: "ITS",
    PersoninCharge_x0028_PIC_x0029_: "Ben Yip",
    Email: "benyip@hku.hk",
    Purpose: "Admin",
    DeploymentType: "Hybrid",
    AIPlatform: "OpenAI",
    AITools: "ChatGPT",
    AISubscriptionPlan: "Azure OpenAI",
    EstimatedCost_x0028_HKD_x0029_: 34000,
    InvolvesPII: "No",
    Created: "2026-02-10T13:20:00Z"
  },
  {
    ID: 7,
    Title: "Automated Grading for Programming Assignments",
    Faculty_x002f_Department: "Faculty of Engineering",
    PersoninCharge_x0028_PIC_x0029_: "Prof. Jason Wong",
    Email: "jasonwong@hku.hk",
    Purpose: "Teaching & Learning",
    DeploymentType: "Inhouse",
    AIPlatform: "HKU HPC",
    AITools: "GitHub Copilot / LLM API",
    AISubscriptionPlan: "",
    EstimatedCost_x0028_HKD_x0029_: 28000,
    InvolvesPII: "Yes",
    Created: "2026-02-14T11:00:00Z"
  },
  {
    ID: 8,
    Title: "Natural Language Processing for Clinical Notes",
    Faculty_x002f_Department: "Li Ka Shing Faculty of Medicine",
    PersoninCharge_x0028_PIC_x0029_: "Dr. Sophia Chow",
    Email: "sophiachow@hku.hk",
    Purpose: "Research",
    DeploymentType: "Inhouse",
    AIPlatform: "HKU HPC",
    AITools: "Llama 3",
    AISubscriptionPlan: "",
    EstimatedCost_x0028_HKD_x0029_: 120000,
    InvolvesPII: "Yes",
    Created: "2026-02-18T09:30:00Z"
  },
  {
    ID: 9,
    Title: "Multilingual Teaching Assistant — Cantonese/English",
    Faculty_x002f_Department: "CAES",
    PersoninCharge_x0028_PIC_x0029_: "Dr. Elaine Chan",
    Email: "elainechan@hku.hk",
    Purpose: "Teaching & Learning",
    DeploymentType: "SaaS",
    AIPlatform: "Google",
    AITools: "Gemini",
    AISubscriptionPlan: "Google Workspace AI",
    EstimatedCost_x0028_HKD_x0029_: 15000,
    InvolvesPII: "No",
    Created: "2026-02-25T10:45:00Z"
  },
  {
    ID: 10,
    Title: "AI-Driven Budget Forecast System",
    Faculty_x002f_Department: "Registry",
    PersoninCharge_x0028_PIC_x0029_: "Ms. Helen Kwok",
    Email: "helenkwok@hku.hk",
    Purpose: "Admin",
    DeploymentType: "SaaS",
    AIPlatform: "Microsoft Azure",
    AITools: "MS Copilot",
    AISubscriptionPlan: "Microsoft 365 Copilot",
    EstimatedCost_x0028_HKD_x0029_: 38000,
    InvolvesPII: "Yes",
    Created: "2026-03-04T14:30:00Z"
  },
  {
    ID: 11,
    Title: "Generative AI for Architectural Design Ideation",
    Faculty_x002f_Department: "Faculty of Architecture",
    PersoninCharge_x0028_PIC_x0029_: "Prof. David Hui",
    Email: "davidhui@hku.hk",
    Purpose: "Teaching & Learning",
    DeploymentType: "SaaS",
    AIPlatform: "Midjourney / OpenAI",
    AITools: "Midjourney",
    AISubscriptionPlan: "Midjourney Standard",
    EstimatedCost_x0028_HKD_x0029_: 9600,
    InvolvesPII: "No",
    Created: "2026-03-08T11:00:00Z"
  },
  {
    ID: 12,
    Title: "Sentiment Analysis of Student Feedback",
    Faculty_x002f_Department: "Faculty of Social Sciences",
    PersoninCharge_x0028_PIC_x0029_: "Dr. Michael Leung",
    Email: "mleung@hku.hk",
    Purpose: "Research",
    DeploymentType: "Hybrid",
    AIPlatform: "OpenAI",
    AITools: "ChatGPT",
    AISubscriptionPlan: "Azure OpenAI",
    EstimatedCost_x0028_HKD_x0029_: 22000,
    InvolvesPII: "Yes",
    Created: "2026-03-12T09:00:00Z"
  },
  {
    ID: 13,
    Title: "Code Review Copilot for Software Engineering Lab",
    Faculty_x002f_Department: "Faculty of Engineering",
    PersoninCharge_x0028_PIC_x0029_: "Dr. Victor Chan",
    Email: "victorchan@hku.hk",
    Purpose: "Teaching & Learning",
    DeploymentType: "SaaS",
    AIPlatform: "Microsoft Azure",
    AITools: "GitHub Copilot",
    AISubscriptionPlan: "GitHub Copilot for Business",
    EstimatedCost_x0028_HKD_x0029_: 16800,
    InvolvesPII: "No",
    Created: "2026-03-18T13:00:00Z"
  },
  {
    ID: 14,
    Title: "On-Premise LLM for Confidential Legal Research",
    Faculty_x002f_Department: "Faculty of Law",
    PersoninCharge_x0028_PIC_x0029_: "Dr. Susan Tse",
    Email: "susantse@hku.hk",
    Purpose: "Research",
    DeploymentType: "Inhouse",
    AIPlatform: "HKU HPC",
    AITools: "Llama 3",
    AISubscriptionPlan: "",
    EstimatedCost_x0028_HKD_x0029_: 85000,
    InvolvesPII: "Yes",
    Created: "2026-03-22T10:30:00Z"
  },
  {
    ID: 15,
    Title: "Personalised Learning Path Recommender",
    Faculty_x002f_Department: "Faculty of Business and Economics",
    PersoninCharge_x0028_PIC_x0029_: "Prof. Anthony Lau",
    Email: "anthonylau@hku.hk",
    Purpose: "Teaching & Learning",
    DeploymentType: "SaaS",
    AIPlatform: "OpenAI",
    AITools: "ChatGPT",
    AISubscriptionPlan: "ChatGPT Edu",
    EstimatedCost_x0028_HKD_x0029_: 24000,
    InvolvesPII: "No",
    Created: "2026-03-28T09:15:00Z"
  },
  {
    ID: 16,
    Title: "HR Recruitment Screening Assistant",
    Faculty_x002f_Department: "Registry",
    PersoninCharge_x0028_PIC_x0029_: "Ms. Grace Poon",
    Email: "gracepoon@hku.hk",
    Purpose: "Admin",
    DeploymentType: "SaaS",
    AIPlatform: "Anthropic",
    AITools: "Claude",
    AISubscriptionPlan: "Claude for Enterprise",
    EstimatedCost_x0028_HKD_x0029_: 48000,
    InvolvesPII: "Yes",
    Created: "2026-04-02T14:00:00Z"
  },
  {
    ID: 17,
    Title: "AI-Powered Literature Review Tool",
    Faculty_x002f_Department: "Library",
    PersoninCharge_x0028_PIC_x0029_: "Ms. Irene Fong",
    Email: "irenefong@hku.hk",
    Purpose: "Research",
    DeploymentType: "SaaS",
    AIPlatform: "OpenAI",
    AITools: "ChatGPT",
    AISubscriptionPlan: "Azure OpenAI",
    EstimatedCost_x0028_HKD_x0029_: 19200,
    InvolvesPII: "No",
    Created: "2026-04-07T10:00:00Z"
  },
  {
    ID: 18,
    Title: "Image Captioning for Art History Course",
    Faculty_x002f_Department: "Faculty of Arts",
    PersoninCharge_x0028_PIC_x0029_: "Dr. Teresa Yuen",
    Email: "teresayuen@hku.hk",
    Purpose: "Teaching & Learning",
    DeploymentType: "SaaS",
    AIPlatform: "Google",
    AITools: "Gemini",
    AISubscriptionPlan: "Google AI Studio",
    EstimatedCost_x0028_HKD_x0029_: 6000,
    InvolvesPII: "No",
    Created: "2026-04-10T11:30:00Z"
  },
  {
    ID: 19,
    Title: "Drug Interaction Prediction Model",
    Faculty_x002f_Department: "Li Ka Shing Faculty of Medicine",
    PersoninCharge_x0028_PIC_x0029_: "Prof. Chris Wong",
    Email: "chriswong@hku.hk",
    Purpose: "Research",
    DeploymentType: "Inhouse",
    AIPlatform: "HKU HPC",
    AITools: "PyTorch / Custom CNN",
    AISubscriptionPlan: "",
    EstimatedCost_x0028_HKD_x0029_: 140000,
    InvolvesPII: "No",
    Created: "2026-04-14T09:00:00Z"
  },
  {
    ID: 20,
    Title: "AI Transcription for Accessibility Services",
    Faculty_x002f_Department: "Registry",
    PersoninCharge_x0028_PIC_x0029_: "Mr. Tommy Lau",
    Email: "tommylau@hku.hk",
    Purpose: "Admin",
    DeploymentType: "SaaS",
    AIPlatform: "Microsoft Azure",
    AITools: "MS Copilot",
    AISubscriptionPlan: "Azure AI Speech",
    EstimatedCost_x0028_HKD_x0029_: 14400,
    InvolvesPII: "Yes",
    Created: "2026-04-17T13:00:00Z"
  },
  {
    ID: 21,
    Title: "Dental X-ray Anomaly Detection",
    Faculty_x002f_Department: "Faculty of Dentistry",
    PersoninCharge_x0028_PIC_x0029_: "Dr. Jenny Ho",
    Email: "jennyho@hku.hk",
    Purpose: "Research",
    DeploymentType: "Inhouse",
    AIPlatform: "HKU HPC",
    AITools: "PyTorch / Custom CNN",
    AISubscriptionPlan: "",
    EstimatedCost_x0028_HKD_x0029_: 88000,
    InvolvesPII: "Yes",
    Created: "2026-04-22T10:15:00Z"
  },
  {
    ID: 22,
    Title: "AI Writing Coach for Business Students",
    Faculty_x002f_Department: "Faculty of Business and Economics",
    PersoninCharge_x0028_PIC_x0029_: "Prof. Linda Siu",
    Email: "lindasiu@hku.hk",
    Purpose: "Teaching & Learning",
    DeploymentType: "SaaS",
    AIPlatform: "Anthropic",
    AITools: "Claude",
    AISubscriptionPlan: "Claude Pro",
    EstimatedCost_x0028_HKD_x0029_: 21600,
    InvolvesPII: "No",
    Created: "2026-04-25T14:30:00Z"
  },
  {
    ID: 23,
    Title: "Hybrid RAG System for Policy Q&A",
    Faculty_x002f_Department: "ITS",
    PersoninCharge_x0028_PIC_x0029_: "Ken Ma",
    Email: "kenma@hku.hk",
    Purpose: "Admin",
    DeploymentType: "Hybrid",
    AIPlatform: "OpenAI",
    AITools: "ChatGPT",
    AISubscriptionPlan: "Azure OpenAI",
    EstimatedCost_x0028_HKD_x0029_: 55000,
    InvolvesPII: "No",
    Created: "2026-04-29T09:30:00Z"
  },
  {
    ID: 24,
    Title: "Genome Sequencing Data Analysis with LLM",
    Faculty_x002f_Department: "Faculty of Science",
    PersoninCharge_x0028_PIC_x0029_: "Dr. Patrick Yim",
    Email: "patrickyim@hku.hk",
    Purpose: "Research",
    DeploymentType: "Inhouse",
    AIPlatform: "HKU HPC",
    AITools: "Llama 3",
    AISubscriptionPlan: "",
    EstimatedCost_x0028_HKD_x0029_: 110000,
    InvolvesPII: "Yes",
    Created: "2026-05-02T11:00:00Z"
  },
  {
    ID: 25,
    Title: "AI-Enabled Course Evaluation Analytics",
    Faculty_x002f_Department: "Faculty of Social Sciences",
    PersoninCharge_x0028_PIC_x0029_: "Dr. Peter Kwok",
    Email: "peterkwok@hku.hk",
    Purpose: "Admin",
    DeploymentType: "Hybrid",
    AIPlatform: "Google",
    AITools: "Gemini",
    AISubscriptionPlan: "Google Workspace AI",
    EstimatedCost_x0028_HKD_x0029_: 27000,
    InvolvesPII: "Yes",
    Created: "2026-05-05T10:00:00Z"
  }
];
